# Generated by Django 4.0.5 on 2022-06-29 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Particulars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('particualrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.ledger')),
            ],
        ),
        migrations.CreateModel(
            name='transactiontype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='contra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instno', models.IntegerField()),
                ('instdate', models.DateField()),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.particulars')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.account')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.ledger')),
                ('transactiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.transactiontype')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallapp.ledger'),
        ),
    ]
