# Generated by Django 4.0 on 2022-09-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallapp', '0004_ledger1_ledger_tax_register_ledger_tax_ledger_sundry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgercreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.CharField(max_length=255)),
                ('bank_details', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('pan_no', models.IntegerField(null=True)),
                ('registration_type', models.CharField(max_length=255, null=True)),
                ('gst_uin', models.IntegerField(null=True)),
                ('set_alter_gstdetails', models.CharField(max_length=255, null=True)),
                ('ac_holder_nm', models.CharField(max_length=255, null=True)),
                ('acc_no', models.IntegerField(null=True)),
                ('ifsc_code', models.IntegerField(null=True)),
                ('swift_code', models.IntegerField(null=True)),
                ('bank_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('SA_cheque_bk', models.CharField(max_length=255, null=True)),
                ('Echeque_p', models.CharField(max_length=255, null=True)),
                ('occ_set_odl', models.CharField(max_length=255, null=True)),
                ('occ_ac_holder_nm', models.CharField(max_length=255, null=True)),
                ('occ_acc_no', models.IntegerField(null=True)),
                ('occ_ifsc_code', models.IntegerField(null=True)),
                ('occ_swift_code', models.IntegerField(null=True)),
                ('occ_bank_name', models.CharField(max_length=255, null=True)),
                ('occ_branch', models.CharField(max_length=255, null=True)),
                ('occ_SA_cheque_bk', models.CharField(max_length=255, null=True)),
                ('occ_Echeque_p', models.CharField(max_length=255, null=True)),
                ('od_set_odl', models.CharField(max_length=255, null=True)),
                ('od_ac_holder_nm', models.CharField(max_length=255, null=True)),
                ('od_acc_no', models.IntegerField(null=True)),
                ('od_ifsc_code', models.IntegerField(null=True)),
                ('od_swift_code', models.IntegerField(null=True)),
                ('od_bank_name', models.CharField(max_length=255, null=True)),
                ('od_branch', models.CharField(max_length=255, null=True)),
                ('od_SA_cheque_bk', models.CharField(max_length=255, null=True)),
                ('od_Echeque_p', models.CharField(max_length=255, null=True)),
                ('statutory_details', models.CharField(max_length=255, null=True)),
                ('type_of_ledger', models.CharField(max_length=100, null=True)),
                ('rounding_method', models.CharField(max_length=100, null=True)),
                ('rounding_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('GST_Applicable', models.CharField(max_length=100, null=True)),
                ('Alter_GST_Details', models.CharField(max_length=100, null=True)),
                ('Appropriate', models.CharField(max_length=100, null=True)),
                ('Types_of_supply', models.CharField(max_length=100, null=True)),
                ('type_duty_tax', models.CharField(max_length=100, null=True)),
                ('tax_type', models.CharField(max_length=100, null=True)),
                ('percentage_of_calcution', models.CharField(max_length=100, null=True)),
                ('rond_method', models.CharField(max_length=100, null=True)),
                ('rond_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('balance_billbybill', models.CharField(max_length=100, null=True)),
                ('credit_period', models.CharField(max_length=100, null=True)),
                ('creditdays_voucher', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ledger_banking_details',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_mailing_address',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_rounding',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_satutory',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_sundry',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_tax_register',
            name='ledger_id',
        ),
        migrations.DeleteModel(
            name='Ledger1',
        ),
        migrations.DeleteModel(
            name='Ledger_Banking_Details',
        ),
        migrations.DeleteModel(
            name='Ledger_Mailing_Address',
        ),
        migrations.DeleteModel(
            name='Ledger_Rounding',
        ),
        migrations.DeleteModel(
            name='Ledger_Satutory',
        ),
        migrations.DeleteModel(
            name='Ledger_sundry',
        ),
        migrations.DeleteModel(
            name='ledger_tax',
        ),
        migrations.DeleteModel(
            name='Ledger_Tax_Register',
        ),
    ]
